# santa :: azure-devops

name: $(date:yyyyMMdd).$(rev:rr)

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - .azure/builds/angular.yaml
    - .azure/triggers/aliciaAngular.yaml
    - AliciaBux.App

pr:
  branches:
    exclude:
    - "*"

stages:
- template: .azure/builds/angular.yaml
  parameters:
    id: $(id)
