# santa :: azure-devops

name: $(date:yyyyMMdd).$(rev:rr)

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - .azure/builds/api.yaml
    - .azure/triggers/aliciaApi.yaml
    - AliciaBux.Api/AliciaBux

pr:
  branches:
    exclude:
    - "*"

stages:
- template: .azure/builds/api.yaml
  parameters:
    id: $(id)
