name: Build and Deploy aliciabuxapi
on:
  push:
    # see https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-including-paths
    branches:
    - main

env:
  AZURE_WEBAPP_NAME: aliciabux
  AZURE_WEBAPP_PATH: AliciaBux-App
  AZURE_WEBAPP_PACKAGE_PATH: './dist/AliciaBux-App'
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.aliciabux_f3d9 }}
  AZURE_API_NAME: aliciabuxapi
  AZURE_API_PACKAGE_PATH: Alicia.Api/publish
  AZURE_API_PUBLISH_PROFILE: ${{ secrets.aliciabuxapi_6c90 }}
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 5.0.x
  API_WORKING_DIRECTORY: AliciaBux-Api/AliciaBux
  WEBAPP_WORKING_DIRECTORY: ./AliciaBux-App

jobs:
  build-and-deploy-asp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore "${{ env.API_WORKING_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ env.API_WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    #- name: Test
    #  run: dotnet test "${{ env.WORKING_DIRECTORY }}" --no-build
    - name: Publish
      run: dotnet publish "${{ env.API_WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_API_PACKAGE_PATH }}"
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_API_NAME }}
        package: ${{ env.AZURE_API_PACKAGE_PATH }}
        publish-profile: ${{ env.AZURE_API_PUBLISH_PROFILE }}
    - name: Publish Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: webapp
        path: ${{ env.AZURE_API_PACKAGE_PATH }}
  build-and-deploy-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.WEBAPP_WORKING_DIRECTORY }}
      - name: Build
        run: npm run build -- --prod
        working-directory: ${{ env.WEBAPP_WORKING_DIRECTORY }}
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        working-directory: ${{ env.WEBAPP_WORKING_DIRECTORY }}
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH}}
